# Generated by Django 3.0.5 on 2020-06-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='recipe.Recipe'),
        ),
    ]
